doctrine:
    dbal:
        types:
            date: 'SprintF\Bundle\Datetime\Doctrine\DBAL\Types\DateType'
            datetime: 'SprintF\Bundle\Datetime\Doctrine\DBAL\Types\DateTimeType'
            daterange: 'SprintF\Bundle\Datetime\Doctrine\DBAL\Types\DateRangeType'
        mapping_types:
            date: date
            datetime: datetime
            daterange: daterange
    orm:
        dql:
            string_functions:
                daterange_contains_date: 'SprintF\Bundle\Datetime\Doctrine\ORM\Query\AST\Functions\DateRangeContainsDate'
                daterange_intersects: 'SprintF\Bundle\Datetime\Doctrine\ORM\Query\AST\Functions\DateRangeIntersects'
                daterange_lower: 'SprintF\Bundle\Datetime\Doctrine\ORM\Query\AST\Functions\DateRangeLower'
                daterange_upper: 'SprintF\Bundle\Datetime\Doctrine\ORM\Query\AST\Functions\DateRangeUpper'